<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="DESKTOP-ME2HPKL" name="AdvisorTest.A_ValidatePublishEquityCashCall" tests="9" failures="2" timestamp="2020-12-31T17:05:10 IST" time="53.880" errors="1">
  <testcase name="validateEditCall" time="0.010" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at AdvisorTest.A_ValidatePublishEquityCashCall.validateEditCall(A_ValidatePublishEquityCashCall.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateEditCall -->
  <system-out/>
  <testcase name="validateSuccessfullCreationOfEquityCashCall" time="53.190" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at PageObject_Advisor.A_EquityCashCallPage.getPublishCallWhenThereISSufficientBalance(A_EquityCashCallPage.java:238)
at AdvisorTest.A_ValidatePublishEquityCashCall.validateSuccessfullCreationOfEquityCashCall(A_ValidatePublishEquityCashCall.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateSuccessfullCreationOfEquityCashCall -->
  <system-out/>
  <testcase name="validateCreatedActiveCallDisplayed" time="0.680" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <failure type="java.lang.AssertionError" message="expected [INANISEC] but found [TCS]">
      <![CDATA[java.lang.AssertionError: expected [INANISEC] but found [TCS]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at PageObject_Advisor.A_AdvisorDashBoardPage.checkCreatedCallScriptName(A_AdvisorDashBoardPage.java:345)
at AdvisorTest.A_ValidatePublishEquityCashCall.validateCreatedActiveCallDisplayed(A_ValidatePublishEquityCashCall.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCreatedActiveCallDisplayed -->
  <system-out/>
  <testcase name="validateDefaultTimeFrameforEquityCashCallIIsIntradayWhenCallTypeIsSell" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateDefaultTimeFrameforEquityCashCallIIsIntradayWhenCallTypeIsSell -->
  <system-out/>
  <testcase name="validateCreatedAwaitingCallDisplayed" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateCreatedAwaitingCallDisplayed -->
  <system-out/>
  <testcase name="validateSuccessfulCreationOfCallWithRecommendedPriceSellType" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateSuccessfulCreationOfCallWithRecommendedPriceSellType -->
  <system-out/>
  <testcase name="validateUnsuccessfulCreationOfCallAfterMarketTime" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateUnsuccessfulCreationOfCallAfterMarketTime -->
  <system-out/>
  <testcase name="validateSuccessfullCreationOfEquityCashCallBuyType" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateSuccessfullCreationOfEquityCashCallBuyType -->
  <system-out/>
  <testcase name="validateSuccessfulCreationOfCallWithRecommendedPrice" classname="AdvisorTest.A_ValidatePublishEquityCashCall">
    <skipped/>
  </testcase> <!-- validateSuccessfulCreationOfCallWithRecommendedPrice -->
  <system-out/>
</testsuite> <!-- AdvisorTest.A_ValidatePublishEquityCashCall -->
