<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-ME2HPKL" name="AdvisorTest.A_ValidatePublishEquityFutureCall" tests="8" failures="1" timestamp="2021-01-04T12:32:27 IST" time="24.418" errors="0">
  <testcase name="validateEquityFutureTitle" time="9.257" classname="AdvisorTest.A_ValidatePublishEquityFutureCall"/>
  <system-out/>
  <testcase name="validateCreateFutureCashCallTitle" time="1.847" classname="AdvisorTest.A_ValidatePublishEquityFutureCall"/>
  <system-out/>
  <testcase name="validateSuccessfullCreationOfCall1" time="10.290" classname="AdvisorTest.A_ValidatePublishEquityFutureCall"/>
  <system-out/>
  <testcase name="validateCreatedAwaitingCallDisplayed" time="0.379" classname="AdvisorTest.A_ValidatePublishEquityFutureCall">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at AdvisorTest.A_ValidatePublishEquityFutureCall.validateCreatedAwaitingCallDisplayed(A_ValidatePublishEquityFutureCall.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCreatedAwaitingCallDisplayed -->
  <system-out/>
  <testcase name="validateEditCall" time="2.645" classname="AdvisorTest.A_ValidatePublishEquityFutureCall"/>
  <system-out/>
  <testcase name="validateSuccessfullCreationOfCall4" classname="AdvisorTest.A_ValidatePublishEquityFutureCall">
    <skipped/>
  </testcase> <!-- validateSuccessfullCreationOfCall4 -->
  <system-out/>
  <testcase name="validateSuccessfullCreationOfCall3" classname="AdvisorTest.A_ValidatePublishEquityFutureCall">
    <skipped/>
  </testcase> <!-- validateSuccessfullCreationOfCall3 -->
  <system-out/>
  <testcase name="validateSuccessfullCreationOfCall2" classname="AdvisorTest.A_ValidatePublishEquityFutureCall">
    <skipped/>
  </testcase> <!-- validateSuccessfullCreationOfCall2 -->
  <system-out/>
</testsuite> <!-- AdvisorTest.A_ValidatePublishEquityFutureCall -->
